// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/gameservice.proto

package go_micro_srv_gameservice

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_gameservice_f2a321a65a577f1c, []int{0}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type CreateGameRequest struct {
	Hometeam             string   `protobuf:"bytes,1,opt,name=hometeam,proto3" json:"hometeam,omitempty"`
	Awayteam             string   `protobuf:"bytes,2,opt,name=awayteam,proto3" json:"awayteam,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGameRequest) Reset()         { *m = CreateGameRequest{} }
func (m *CreateGameRequest) String() string { return proto.CompactTextString(m) }
func (*CreateGameRequest) ProtoMessage()    {}
func (*CreateGameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_gameservice_f2a321a65a577f1c, []int{1}
}
func (m *CreateGameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGameRequest.Unmarshal(m, b)
}
func (m *CreateGameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGameRequest.Marshal(b, m, deterministic)
}
func (dst *CreateGameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGameRequest.Merge(dst, src)
}
func (m *CreateGameRequest) XXX_Size() int {
	return xxx_messageInfo_CreateGameRequest.Size(m)
}
func (m *CreateGameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGameRequest proto.InternalMessageInfo

func (m *CreateGameRequest) GetHometeam() string {
	if m != nil {
		return m.Hometeam
	}
	return ""
}

func (m *CreateGameRequest) GetAwayteam() string {
	if m != nil {
		return m.Awayteam
	}
	return ""
}

type Game struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Score                string   `protobuf:"bytes,2,opt,name=score,proto3" json:"score,omitempty"`
	Attendance           int32    `protobuf:"varint,3,opt,name=attendance,proto3" json:"attendance,omitempty"`
	Quarter              string   `protobuf:"bytes,4,opt,name=quarter,proto3" json:"quarter,omitempty"`
	TotalrunPlays        int32    `protobuf:"varint,5,opt,name=totalrunPlays,proto3" json:"totalrunPlays,omitempty"`
	Title                string   `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game) Reset()         { *m = Game{} }
func (m *Game) String() string { return proto.CompactTextString(m) }
func (*Game) ProtoMessage()    {}
func (*Game) Descriptor() ([]byte, []int) {
	return fileDescriptor_gameservice_f2a321a65a577f1c, []int{2}
}
func (m *Game) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game.Unmarshal(m, b)
}
func (m *Game) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game.Marshal(b, m, deterministic)
}
func (dst *Game) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game.Merge(dst, src)
}
func (m *Game) XXX_Size() int {
	return xxx_messageInfo_Game.Size(m)
}
func (m *Game) XXX_DiscardUnknown() {
	xxx_messageInfo_Game.DiscardUnknown(m)
}

var xxx_messageInfo_Game proto.InternalMessageInfo

func (m *Game) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Game) GetScore() string {
	if m != nil {
		return m.Score
	}
	return ""
}

func (m *Game) GetAttendance() int32 {
	if m != nil {
		return m.Attendance
	}
	return 0
}

func (m *Game) GetQuarter() string {
	if m != nil {
		return m.Quarter
	}
	return ""
}

func (m *Game) GetTotalrunPlays() int32 {
	if m != nil {
		return m.TotalrunPlays
	}
	return 0
}

func (m *Game) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type GameResponse struct {
	Game                 *Game    `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameResponse) Reset()         { *m = GameResponse{} }
func (m *GameResponse) String() string { return proto.CompactTextString(m) }
func (*GameResponse) ProtoMessage()    {}
func (*GameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_gameservice_f2a321a65a577f1c, []int{3}
}
func (m *GameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameResponse.Unmarshal(m, b)
}
func (m *GameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameResponse.Marshal(b, m, deterministic)
}
func (dst *GameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameResponse.Merge(dst, src)
}
func (m *GameResponse) XXX_Size() int {
	return xxx_messageInfo_GameResponse.Size(m)
}
func (m *GameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GameResponse proto.InternalMessageInfo

func (m *GameResponse) GetGame() *Game {
	if m != nil {
		return m.Game
	}
	return nil
}

type GameCreatedResponse struct {
	Created              bool     `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Game                 *Game    `protobuf:"bytes,2,opt,name=game,proto3" json:"game,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameCreatedResponse) Reset()         { *m = GameCreatedResponse{} }
func (m *GameCreatedResponse) String() string { return proto.CompactTextString(m) }
func (*GameCreatedResponse) ProtoMessage()    {}
func (*GameCreatedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_gameservice_f2a321a65a577f1c, []int{4}
}
func (m *GameCreatedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameCreatedResponse.Unmarshal(m, b)
}
func (m *GameCreatedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameCreatedResponse.Marshal(b, m, deterministic)
}
func (dst *GameCreatedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameCreatedResponse.Merge(dst, src)
}
func (m *GameCreatedResponse) XXX_Size() int {
	return xxx_messageInfo_GameCreatedResponse.Size(m)
}
func (m *GameCreatedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GameCreatedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GameCreatedResponse proto.InternalMessageInfo

func (m *GameCreatedResponse) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *GameCreatedResponse) GetGame() *Game {
	if m != nil {
		return m.Game
	}
	return nil
}

type RunPlayRequest struct {
	GameID               int32    `protobuf:"varint,1,opt,name=gameID,proto3" json:"gameID,omitempty"`
	PlayerIDs            []int32  `protobuf:"varint,2,rep,packed,name=playerIDs,proto3" json:"playerIDs,omitempty"`
	PlayFormation        string   `protobuf:"bytes,3,opt,name=playFormation,proto3" json:"playFormation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunPlayRequest) Reset()         { *m = RunPlayRequest{} }
func (m *RunPlayRequest) String() string { return proto.CompactTextString(m) }
func (*RunPlayRequest) ProtoMessage()    {}
func (*RunPlayRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_gameservice_f2a321a65a577f1c, []int{5}
}
func (m *RunPlayRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunPlayRequest.Unmarshal(m, b)
}
func (m *RunPlayRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunPlayRequest.Marshal(b, m, deterministic)
}
func (dst *RunPlayRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunPlayRequest.Merge(dst, src)
}
func (m *RunPlayRequest) XXX_Size() int {
	return xxx_messageInfo_RunPlayRequest.Size(m)
}
func (m *RunPlayRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RunPlayRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RunPlayRequest proto.InternalMessageInfo

func (m *RunPlayRequest) GetGameID() int32 {
	if m != nil {
		return m.GameID
	}
	return 0
}

func (m *RunPlayRequest) GetPlayerIDs() []int32 {
	if m != nil {
		return m.PlayerIDs
	}
	return nil
}

func (m *RunPlayRequest) GetPlayFormation() string {
	if m != nil {
		return m.PlayFormation
	}
	return ""
}

type Result struct {
	NetYardGain          int32    `protobuf:"varint,1,opt,name=netYardGain,proto3" json:"netYardGain,omitempty"`
	Down                 string   `protobuf:"bytes,2,opt,name=down,proto3" json:"down,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_gameservice_f2a321a65a577f1c, []int{6}
}
func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (dst *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(dst, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetNetYardGain() int32 {
	if m != nil {
		return m.NetYardGain
	}
	return 0
}

func (m *Result) GetDown() string {
	if m != nil {
		return m.Down
	}
	return ""
}

type ResultResponse struct {
	Result               *Result  `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResultResponse) Reset()         { *m = ResultResponse{} }
func (m *ResultResponse) String() string { return proto.CompactTextString(m) }
func (*ResultResponse) ProtoMessage()    {}
func (*ResultResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_gameservice_f2a321a65a577f1c, []int{7}
}
func (m *ResultResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResultResponse.Unmarshal(m, b)
}
func (m *ResultResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResultResponse.Marshal(b, m, deterministic)
}
func (dst *ResultResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResultResponse.Merge(dst, src)
}
func (m *ResultResponse) XXX_Size() int {
	return xxx_messageInfo_ResultResponse.Size(m)
}
func (m *ResultResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResultResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResultResponse proto.InternalMessageInfo

func (m *ResultResponse) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

type EmptyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyResponse) Reset()         { *m = EmptyResponse{} }
func (m *EmptyResponse) String() string { return proto.CompactTextString(m) }
func (*EmptyResponse) ProtoMessage()    {}
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_gameservice_f2a321a65a577f1c, []int{8}
}
func (m *EmptyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyResponse.Unmarshal(m, b)
}
func (m *EmptyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyResponse.Marshal(b, m, deterministic)
}
func (dst *EmptyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyResponse.Merge(dst, src)
}
func (m *EmptyResponse) XXX_Size() int {
	return xxx_messageInfo_EmptyResponse.Size(m)
}
func (m *EmptyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Empty)(nil), "go.micro.srv.gameservice.Empty")
	proto.RegisterType((*CreateGameRequest)(nil), "go.micro.srv.gameservice.CreateGameRequest")
	proto.RegisterType((*Game)(nil), "go.micro.srv.gameservice.Game")
	proto.RegisterType((*GameResponse)(nil), "go.micro.srv.gameservice.GameResponse")
	proto.RegisterType((*GameCreatedResponse)(nil), "go.micro.srv.gameservice.GameCreatedResponse")
	proto.RegisterType((*RunPlayRequest)(nil), "go.micro.srv.gameservice.RunPlayRequest")
	proto.RegisterType((*Result)(nil), "go.micro.srv.gameservice.Result")
	proto.RegisterType((*ResultResponse)(nil), "go.micro.srv.gameservice.ResultResponse")
	proto.RegisterType((*EmptyResponse)(nil), "go.micro.srv.gameservice.EmptyResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for GameService service

type GameServiceClient interface {
	StartGame(ctx context.Context, in *Empty, opts ...client.CallOption) (*EmptyResponse, error)
	RunPlay(ctx context.Context, in *Empty, opts ...client.CallOption) (*EmptyResponse, error)
}

type gameServiceClient struct {
	c           client.Client
	serviceName string
}

func NewGameServiceClient(serviceName string, c client.Client) GameServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.srv.gameservice"
	}
	return &gameServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *gameServiceClient) StartGame(ctx context.Context, in *Empty, opts ...client.CallOption) (*EmptyResponse, error) {
	req := c.c.NewRequest(c.serviceName, "GameService.StartGame", in)
	out := new(EmptyResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) RunPlay(ctx context.Context, in *Empty, opts ...client.CallOption) (*EmptyResponse, error) {
	req := c.c.NewRequest(c.serviceName, "GameService.RunPlay", in)
	out := new(EmptyResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GameService service

type GameServiceHandler interface {
	StartGame(context.Context, *Empty, *EmptyResponse) error
	RunPlay(context.Context, *Empty, *EmptyResponse) error
}

func RegisterGameServiceHandler(s server.Server, hdlr GameServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&GameService{hdlr}, opts...))
}

type GameService struct {
	GameServiceHandler
}

func (h *GameService) StartGame(ctx context.Context, in *Empty, out *EmptyResponse) error {
	return h.GameServiceHandler.StartGame(ctx, in, out)
}

func (h *GameService) RunPlay(ctx context.Context, in *Empty, out *EmptyResponse) error {
	return h.GameServiceHandler.RunPlay(ctx, in, out)
}

func init() {
	proto.RegisterFile("proto/gameservice.proto", fileDescriptor_gameservice_f2a321a65a577f1c)
}

var fileDescriptor_gameservice_f2a321a65a577f1c = []byte{
	// 438 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x25, 0x6e, 0xec, 0x34, 0x13, 0x1a, 0xc4, 0x82, 0x60, 0x55, 0xa1, 0x12, 0xad, 0x90, 0xe8,
	0xc9, 0x48, 0xe1, 0xc2, 0x89, 0x03, 0x14, 0xaa, 0xc2, 0x05, 0xb9, 0x42, 0x88, 0xe3, 0x62, 0x8f,
	0x8a, 0x25, 0xdb, 0x9b, 0xee, 0x4e, 0x5a, 0xe5, 0x77, 0xf8, 0x0f, 0xfe, 0x0d, 0xed, 0xec, 0xda,
	0x24, 0x87, 0x08, 0x21, 0xf5, 0x96, 0xf7, 0x66, 0xde, 0x7b, 0xd9, 0xb7, 0x6b, 0x78, 0xba, 0xb2,
	0x86, 0xcc, 0xab, 0x2b, 0xdd, 0xa2, 0x43, 0x7b, 0x53, 0x97, 0x98, 0x33, 0x23, 0xe4, 0x95, 0xc9,
	0xdb, 0xba, 0xb4, 0x26, 0x77, 0xf6, 0x26, 0xdf, 0x9a, 0xab, 0x09, 0xa4, 0x1f, 0xda, 0x15, 0x6d,
	0xd4, 0x67, 0x78, 0xf8, 0xde, 0xa2, 0x26, 0x3c, 0xd7, 0x2d, 0x16, 0x78, 0xbd, 0x46, 0x47, 0xe2,
	0x18, 0x0e, 0x7f, 0x9a, 0x16, 0x09, 0x75, 0x2b, 0x47, 0x8b, 0xd1, 0xe9, 0xb4, 0x18, 0xb0, 0x9f,
	0xe9, 0x5b, 0xbd, 0xe1, 0x59, 0x12, 0x66, 0x3d, 0x56, 0xbf, 0x46, 0x30, 0xf6, 0x3e, 0x62, 0x0e,
	0x49, 0x5d, 0xb1, 0x34, 0x2d, 0x92, 0xba, 0x12, 0x8f, 0x21, 0x75, 0xa5, 0xb1, 0x18, 0x15, 0x01,
	0x88, 0x13, 0x00, 0x4d, 0x84, 0x5d, 0xa5, 0xbb, 0x12, 0xe5, 0x01, 0x6f, 0x6f, 0x31, 0x42, 0xc2,
	0xe4, 0x7a, 0xad, 0x2d, 0xa1, 0x95, 0x63, 0xd6, 0xf5, 0x50, 0xbc, 0x80, 0x23, 0x32, 0xa4, 0x1b,
	0xbb, 0xee, 0xbe, 0x34, 0x7a, 0xe3, 0x64, 0xca, 0xe2, 0x5d, 0xd2, 0xa7, 0x52, 0x4d, 0x0d, 0xca,
	0x2c, 0xa4, 0x32, 0x50, 0xef, 0xe0, 0x7e, 0x38, 0xab, 0x5b, 0x99, 0xce, 0xa1, 0x58, 0xc2, 0xd8,
	0x37, 0xc3, 0xff, 0x76, 0xb6, 0x3c, 0xc9, 0xf7, 0x75, 0x96, 0xb3, 0x8a, 0x77, 0x55, 0x09, 0x8f,
	0x3c, 0x0a, 0xcd, 0x55, 0x83, 0x95, 0x84, 0x49, 0x19, 0x28, 0x76, 0x3b, 0x2c, 0x7a, 0x38, 0x84,
	0x24, 0xff, 0x11, 0xd2, 0xc0, 0xbc, 0x08, 0x47, 0xe9, 0xef, 0xe5, 0x09, 0x64, 0x7e, 0x72, 0x71,
	0x16, 0xab, 0x8d, 0x48, 0x3c, 0x83, 0xe9, 0xaa, 0xd1, 0x1b, 0xb4, 0x17, 0x67, 0x4e, 0x26, 0x8b,
	0x83, 0xd3, 0xb4, 0xf8, 0x4b, 0xf8, 0xb2, 0x3c, 0xf8, 0x68, 0x6c, 0xab, 0xa9, 0x36, 0x1d, 0x37,
	0x3d, 0x2d, 0x76, 0x49, 0xf5, 0x16, 0xb2, 0x02, 0xdd, 0xba, 0x21, 0xb1, 0x80, 0x59, 0x87, 0xf4,
	0x5d, 0xdb, 0xea, 0x5c, 0xd7, 0x5d, 0x8c, 0xda, 0xa6, 0x84, 0x80, 0x71, 0x65, 0x6e, 0xbb, 0x78,
	0x9b, 0xfc, 0x5b, 0x7d, 0x82, 0x79, 0xd0, 0x0f, 0x6d, 0xbc, 0x81, 0xcc, 0x32, 0x13, 0xab, 0x5d,
	0xec, 0x3f, 0x75, 0x54, 0xc6, 0x7d, 0xf5, 0x00, 0x8e, 0xf8, 0x75, 0xf6, 0x56, 0xcb, 0xdf, 0x23,
	0x98, 0xf9, 0x66, 0x2e, 0xc3, 0xbe, 0xf8, 0x06, 0xd3, 0x4b, 0xd2, 0x96, 0xf8, 0xb1, 0x3d, 0xdf,
	0xef, 0xcb, 0x2e, 0xc7, 0x2f, 0xff, 0xb1, 0xd0, 0xc7, 0xa8, 0x7b, 0xe2, 0x2b, 0x4c, 0x62, 0xe7,
	0x77, 0x69, 0xfb, 0x23, 0xe3, 0xef, 0xf1, 0xf5, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa9, 0xa7,
	0x95, 0x87, 0xaa, 0x03, 0x00, 0x00,
}
